CXX := clang++
# NOTE: -MMD and -MP are used to generate a list of (header and source)
# dependencies for each object file and header file. These have the `.d`
# extension.
CXXFLAGS := -std=c++20 -Wall -Wextra -MMD -MP -Isrc

# NOTE: Phony targets are targets that aren't actual files. If you don't
# declare this, and there's a file named "clean" in your directory, then
# running `make clean` will cause Make to try to build that file, instead
# of the `clean` target.
.PHONY: clean all test

# NOTE: The first target is always the default target, i.e., the target that
# is built when you just run `make` without any arguments.
APP := loxc
all: $(APP)

SRCS := $(wildcard src/*.cpp)
OBJS := $(SRCS:.cpp=.o)
DEPS := $(SRCS:.cpp=.d)
# NOTE: This line will include the dependency files generated by the -MMD flag.
# That means that we don't need to manually specify dependencies here: we let
# Clang figure it out, and include the generated files.
-include $(DEPS)

# NOTE: The dependency files only tell Make which files depend on which files. It
# doesn't include instructions for actually building the object files. In fact,
# Make has a built-in rule for building `.o` files from `.cpp` files, so we could
# get away without specifying it; but it's probably better to be explicit.
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

APP_OBJS := app/main.o
$(APP): $(OBJS) $(APP_OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

TEST_SRCS := $(wildcard tests/*.cpp)
TEST_OBJS := $(TEST_SRCS:.cpp=.o)
TEST_DEPS := $(TEST_SRCS:.cpp=.d)
-include $(TEST_DEPS)
TEST_RUNNER_EXECUTABLE := tests/test_runner
# NOTE: I had to find the name `catch2-with-main` by inspecting the contents of
# $(brew --prefix catch2)/share/pkgconfig. Homebrew doesn't really expose this to
# you (even though it does install catch2-with-main when you install catch 2).
CATCH2_FLAGS := $(shell pkg-config --cflags --libs catch2-with-main)
# NOTE: $(CATCH2_FLAGS) MUST come after the object files, because the linker
# needs to see the object files first to know what symbols are needed from the
# Catch2 library. It can't 'revisit' older object files to resolve symbols.
$(TEST_RUNNER_EXECUTABLE): $(OBJS) $(TEST_OBJS)
	$(CXX) $(TEST_CXXFLAGS) -o $(TEST_RUNNER_EXECUTABLE) $^ $(CATCH2_FLAGS)

test: $(APP) $(TEST_RUNNER_EXECUTABLE)
	./$(TEST_RUNNER_EXECUTABLE)

clean:
	rm -f $(APP_OBJS) $(OBJS) $(TEST_OBJS) $(DEPS) $(TEST_DEPS) $(APP) $(TEST_RUNNER_EXECUTABLE)
