CXX := clang++
# NOTE: -MMD and -MP are used to generate a list of (header and source)
# dependencies for each object file and header file. These have the `.d`
# extension.
CXXFLAGS := -std=c++20 -Wall -Wextra -Iinclude -MMD -MP
TARGET := loxc

# NOTE: Phony targets are targets that aren't actual files. If you don't
# declare this, and there's a file named "clean" in your directory, then
# running `make clean` will cause Make to try to build that file, instead
# of the `clean` target.
.PHONY: clean all test

# NOTE: The first target is always the default target, i.e., the target that
# is built when you just run `make` without any arguments.
all: $(TARGET)

SRCS := $(wildcard src/*.cpp)
OBJS := $(SRCS:.cpp=.o)
DEPS := $(SRCS:.cpp=.d)
# NOTE: This line will include the dependency files generated by the -MMD flag.
# That means that we don't need to manually specify dependencies here: we let
# Clang figure it out, and include the generated files.
-include $(DEPS)

# NOTE: The dependency files only tell Make which files depend on which files. It
# doesn't include instructions for actually building the object files. In fact,
# Make has a built-in rule for building `.o` files from `.cpp` files, so we could
# get away without specifying it; but it's probably better to be explicit.
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

TEST_RUNNER_EXECUTABLE := tests/test_runner
# NOTE: I had to find the name `catch2-with-main` by inspecting the contents of
# $(brew --prefix catch2)/share/pkgconfig. Homebrew doesn't really expose this to
# you (even though it does install catch2-with-main when you install catch 2).
CATCH2_FLAGS := $(shell pkg-config --cflags --libs catch2-with-main)
$(TEST_RUNNER_EXECUTABLE): tests/main.cpp
	$(CXX) $(CXXFLAGS) $(CATCH2_FLAGS) -o $(TEST_RUNNER_EXECUTABLE) tests/main.cpp

test: $(TARGET) $(TEST_RUNNER_EXECUTABLE)
	./$(TEST_RUNNER_EXECUTABLE)

clean:
	rm -f $(OBJS) $(DEPS) $(TARGET) tests/test_runner

